### ISSUE TITLE
[Bug] Name validation can be kinda bypassed

### ISSUE THREAD

**Issue by Vilder50** [Plagiatus/MaptestingBot#15]
**Bug:**
When you use the !register command it's possible to kinda bypass the validation. This is done by doing 
`!register Java [your actual Minecraft ign]?whatever-you-want-to-type-here`.

**Explanation:**
The bot is adding the username directly to the Minecraft API url. The Minecraft API doesn't care about extra queries in the link so everything after the ? is ignored by the API. The API will say `Vilder50?blabla` is valid and the bot will accept it's valid... even though it's not a valid Minecraft name.

**Suggested fix:**
Use a regex to validate if the given name even could be a Minecraft name. `[a-z0-9A-Z_]*` should do it.
Link to command: https://github.com/Plagiatus/MaptestingBot/blob/master/src/commands/register.ts

**extra thoughts:**
You could totally abuse this bug to make the bot post a link when you join someone else's session. Guess it's also possible to make the bot post an image (not 100% sure though).

**Comment by Plagiatus** [comment]
pretty sure you couldn't abuse this in those ways, as the Username will be posted in plaintext. then again, the "plaintext" part is only done through adding ` in the code, which could be mitigated by using the same thing in the "query".
