### ISSUE TITLE
!caniping shows "Infinity hours and NaN minutes" when you have never started a session before

### ISSUE THREAD

**Issue by ErrorCraft** [Plagiatus/MaptestingBot#20]
When you do `!caniping` and you have never started a session before, the bot shows that "you can ping again in Infinity hours and NaN minutes."

I cannot post an image so have the message link: https://discordapp.com/channels/212263499601018880/347323385644187658/708986926153334804

**Comment by Plagiatus** [comment]
I thought it was a fun little thing, but you're probably right, it should say something like "lvl 0 people cannot ping".
